import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import type { Transaction, Category } from '../types';
import { sumByBucket, calculate503020 } from './math/fifty-thirty-twenty';

// ─── CSV export ───────────────────────────────────────────────────────────────

function escapeCsv(value: string | number | undefined | null): string {
  if (value == null) return '';
  const str = String(value);
  return str.includes(',') || str.includes('"') || str.includes('\n')
    ? `"${str.replace(/"/g, '""')}"`
    : str;
}

/**
 * Export a month's transactions to CSV and open the system share sheet.
 */
export async function exportTransactionsCsv(
  transactions: Transaction[],
  month: string,
): Promise<void> {
  const header = ['Date', 'Type', 'Amount', 'Description', 'Category', 'Bucket', 'Account'];
  const rows = transactions.map((tx) => [
    tx.date,
    tx.type,
    tx.amount.toFixed(2),
    tx.description ?? '',
    tx.category?.name ?? '',
    tx.category?.bucket ?? '',
    tx.account?.name ?? '',
  ]);

  const csv = [header, ...rows].map((row) => row.map(escapeCsv).join(',')).join('\n');
  const filename = `finance-tracker-${month}.csv`;
  const path = `${FileSystem.cacheDirectory}${filename}`;

  await FileSystem.writeAsStringAsync(path, csv, { encoding: FileSystem.EncodingType.UTF8 });

  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) throw new Error('Sharing is not available on this device.');

  await Sharing.shareAsync(path, { mimeType: 'text/csv', dialogTitle: `Export ${month}` });
}

// ─── Text summary report ──────────────────────────────────────────────────────

/**
 * Build a plain-text monthly report string.
 */
export function buildMonthlyReport(
  transactions: Transaction[],
  categories: Category[],
  month: string,
): string {
  const label = new Date(`${month}-01`).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
  const income = transactions.filter((t) => t.type === 'income').reduce((s, t) => s + t.amount, 0);
  const expenses = transactions.filter((t) => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
  const net = income - expenses;

  const breakdown = sumByBucket(transactions, categories);
  const health = calculate503020(breakdown);

  // Top 5 expense categories
  const catTotals = new Map<string, { name: string; total: number }>();
  for (const tx of transactions) {
    if (tx.type !== 'expense' || !tx.category_id) continue;
    const cat = tx.category;
    if (!cat) continue;
    const existing = catTotals.get(tx.category_id) ?? { name: cat.name, total: 0 };
    catTotals.set(tx.category_id, { ...existing, total: existing.total + tx.amount });
  }
  const topCategories = [...catTotals.values()]
    .sort((a, b) => b.total - a.total)
    .slice(0, 5);

  const lines = [
    `📊 Finance Tracker — ${label}`,
    '─'.repeat(36),
    '',
    `Income:    $${income.toFixed(2)}`,
    `Expenses:  $${expenses.toFixed(2)}`,
    `Net:       ${net >= 0 ? '+' : ''}$${net.toFixed(2)}`,
    '',
    `50/30/20 Health Score: ${health.score}/100 (${health.label})`,
    `  Needs score:   ${health.bucketScores.needs}/100`,
    `  Wants score:   ${health.bucketScores.wants}/100`,
    `  Savings score: ${health.bucketScores.savings}/100`,
    '',
    'Top Spending Categories:',
    ...topCategories.map((c, i) => `  ${i + 1}. ${c.name} — $${c.total.toFixed(2)}`),
    '',
    'Recommendations:',
    ...health.recommendations.map((r) => `  • ${r}`),
    '',
    `Transactions this month: ${transactions.length}`,
    '─'.repeat(36),
    'Generated by Finance Tracker',
  ];

  return lines.join('\n');
}

/**
 * Share the monthly plain-text report via system share sheet.
 */
export async function shareMonthlyReport(
  transactions: Transaction[],
  categories: Category[],
  month: string,
): Promise<void> {
  const report = buildMonthlyReport(transactions, categories, month);
  const filename = `report-${month}.txt`;
  const path = `${FileSystem.cacheDirectory}${filename}`;

  await FileSystem.writeAsStringAsync(path, report, { encoding: FileSystem.EncodingType.UTF8 });

  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) throw new Error('Sharing is not available on this device.');

  await Sharing.shareAsync(path, { mimeType: 'text/plain', dialogTitle: `Report — ${month}` });
}
